# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SQLite3Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SQLite3Demo
pod 'FMDB'

  target 'SQLite3DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SQLite3DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
